language: node_js
env:
  global:
  - DEVELOPMENT_PATH="/home/travisaw/travisaw.com/utpt/wp-content/themes/unicorns-take-photos-too"
  - PRODUCTION_PATH="/home/travisaw/travisaw.com/utpt/wp-content/themes/unicorns-take-photos-too"
  - SSH_USER="travisaw"
  - SSH_HOST="travisawagner.com"
  - DEPLOY_IGNORE="./scripts/.deployignore"
node_js:
- "node"
cache: npm
addons:
  ssh_known_hosts: travisawagner.com
before_install:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
- openssl aes-256-cbc -K $encrypted_820b785c9344_key -iv $encrypted_820b785c9344_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^dev|master$"
