language: generic
addons:
  ssh_known_hosts: travisawagner.com
before_install:
- openssl aes-256-cbc -K $encrypted_820b785c9344_key -iv $encrypted_820b785c9344_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travisaw@travisawagner.com:/home/travisaw/travisaw.com/utpt/wp-content/theme/unicorns-take-photos-too
  on:
    branch: master
